@startuml

title __AUTH's Class Diagram__\n

  namespace com.ifmo.hatchery {
    namespace model.auth {
      class com.ifmo.hatchery.model.auth.Privilege {
          - id : Long
          - name : String
          - roles : Collection<Role>
          + Privilege()
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace model.auth {
      class com.ifmo.hatchery.model.auth.Role {
          - id : Long
          - name : String
          - privileges : Collection<Privilege>
          - users : Collection<UserX>
          + Role()
          + equals()
          + getAuthority()
          + getId()
          + getName()
          + getPrivileges()
          + getUsers()
          + hashCode()
          + setId()
          + setName()
          + setPrivileges()
          + setUsers()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace model.auth {
      class com.ifmo.hatchery.model.auth.UserX {
          - email : String
          - enabled : boolean
          - id : Long
          - lastName : String
          - password : String
          - passwordConfirm : String
          - roles : Set<Role>
          - tokenExpired : boolean
          - username : String
          + UserX()
          + equals()
          + getAuthorities()
          + getBiomaterialType()
          + getEmail()
          + getId()
          + getLastName()
          + getPassword()
          + getPasswordConfirm()
          + getRoles()
          + getUsername()
          + hashCode()
          + isAccountNonExpired()
          + isAccountNonLocked()
          + isCredentialsNonExpired()
          + isEnabled()
          + isTokenExpired()
          + setBiomaterialType()
          + setEmail()
          + setEnabled()
          + setId()
          + setLastName()
          + setPassword()
          + setPasswordConfirm()
          + setRoles()
          + setTokenExpired()
          + setUsername()
          + toString()
          # canEqual()
      }
    }
  }
  

  com.ifmo.hatchery.model.auth.Role .up.|> org.springframework.security.core.GrantedAuthority
  com.ifmo.hatchery.model.auth.UserX .up.|> org.springframework.security.core.userdetails.UserDetails
  com.ifmo.hatchery.model.auth.UserX o-- com.ifmo.hatchery.model.system.BiomaterialType : biomaterialType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
