@startuml

title __SERVICE's Class Diagram__\n

  namespace com.ifmo.hatchery {
    namespace service {
      class com.ifmo.hatchery.service.BiomaterialService {
          - biomaterialRepository : BiomaterialRepository<Biomaterial, Long>
          + createBiomaterial()
          + findById()
          + findByTypeAndBioState()
          + saveBiomaterial()
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace service {
      class com.ifmo.hatchery.service.DashboardService {
          {static} + NOT_APPLICABLE : String
          - taskRepository : TaskRepository<Task, Long>
          + getTaskMap()
          {static} - filterTaskByStages()
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace service {
      class com.ifmo.hatchery.service.OrderService {
          - orderRepository : OrderRepository<OrderX, Long>
          - taskRepository : TaskRepository<Task, Long>
          + createOrder()
          + findAll()
          + findByCustomer()
          + saveOrder()
          - createTaskAndOrder()
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace service {
      class com.ifmo.hatchery.service.RoleService {
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace service {
      class com.ifmo.hatchery.service.SkillService {
          - skillRepository : SkillRepository<Skill, Long>
          + findAll()
          + findAllById()
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace service {
      class com.ifmo.hatchery.service.TaskService {
          - taskRepository : TaskRepository<Task, Long>
          + getAllByStageAndLock()
          + getAllByStageWithoutLock()
          + getAllTasks()
          + getOneTask()
          + getStageTasks()
          + saveTask()
      }
    }
  }
  

  namespace com.ifmo.hatchery {
    namespace service {
      class com.ifmo.hatchery.service.UserService {
          - em : EntityManager
          - roleRepository : RoleRepository<Role, Long>
          - userRepository : UserRepository<UserX, Long>
          + allUsers()
          + findByUsername()
          + findUserById()
          + loadUserByUsername()
          + saveUser()
          + usergtList()
      }
    }
  }
  

  com.ifmo.hatchery.service.UserService .up.|> org.springframework.security.core.userdetails.UserDetailsService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
